spring:
  datasource:
    crawler:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/crawl_review?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true&autoReconnect=true
      username: root
      password: root

      max-active: 300
      min-idle: 20
      initial-size: 20
      max-wait: 10000
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs-millis: 18800

    mws:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://10.1.1.86:3306/customer_amazon_mws?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true&autoReconnect=true
      username: amazon_customer_mws_email
      password: customerMwsEmail#2018

      max-active: 300
      min-idle: 20
      initial-size: 20
      max-wait: 10000
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs-millis: 18800

    base:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/amazon_customer_base?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true&autoReconnect=true
      username: root
      password: root

      max-idle: 20
      min-idle: 20
      initial-size: 20
      max-wait: 10000
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800

server:
  port: 9256

# 配置客制化的Mapper
mapper:
  mappers:
   - com.aukey.crawler.common.mapper.Mapper
   - com.customer.common.mapper.Mapper